//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_informacje
    {
        public int pk_lek_id_num { get; set; }
        public int inter_id_num { get; set; }
        public int syno_id_num { get; set; }
        public Nullable<int> synozb_id_num { get; set; }
        public int ref_id_num { get; set; }
        public Nullable<bool> bez_rec_bool { get; set; }
        public Nullable<bool> polski_bool { get; set; }
        public Nullable<bool> kosmetyk_bool { get; set; }
        public Nullable<bool> homeo_bool { get; set; }
        public Nullable<bool> diet_bool { get; set; }
        public Nullable<bool> antykonc_bool { get; set; }
        public Nullable<bool> surowiec_bool { get; set; }
        public Nullable<bool> opak_bool { get; set; }
        public Nullable<bool> surowica_bool { get; set; }
        public Nullable<bool> szczep_bool { get; set; }
        public Nullable<bool> iniek_bool { get; set; }
        public Nullable<bool> opatr_bool { get; set; }
        public Nullable<bool> szew_bool { get; set; }
        public Nullable<bool> prot_bool { get; set; }
        public Nullable<bool> diag_bool { get; set; }
        public Nullable<bool> socz_bool { get; set; }
        public Nullable<bool> sanit_bool { get; set; }
        public Nullable<bool> dezyn_bool { get; set; }
        public Nullable<bool> pomoc_bool { get; set; }
        public Nullable<bool> weteryn_bool { get; set; }
        public Nullable<bool> doping_bool { get; set; }
        public Nullable<bool> inny_bool { get; set; }
        public Nullable<System.DateTime> wersja_date { get; set; }
    
        public virtual t_inter t_inter { get; set; }
        public virtual t_leki t_leki { get; set; }
        public virtual t_refundacja t_refundacja { get; set; }
        public virtual t_syno t_syno { get; set; }
    }
}
