//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_leki
    {
        public t_leki()
        {
            this.t_sklad = new HashSet<t_sklad>();
            this.t_produkty = new HashSet<t_produkty>();
        }
    
        public int pk_lek_id_num { get; set; }
        public string nazwa_char { get; set; }
        public string postac_char { get; set; }
        public string opak_char { get; set; }
        public Nullable<int> prod_id_num { get; set; }
        public Nullable<System.DateTime> wersja_date { get; set; }
    
        public virtual t_informacje t_informacje { get; set; }
        public virtual t_producenci t_producenci { get; set; }
        public virtual ICollection<t_sklad> t_sklad { get; set; }
        public virtual ICollection<t_produkty> t_produkty { get; set; }
    }
}
