//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_producenci
    {
        public t_producenci()
        {
            this.t_leki = new HashSet<t_leki>();
        }
    
        public int pk_prod_id_num { get; set; }
        public string nazwa_char { get; set; }
    
        public virtual ICollection<t_leki> t_leki { get; set; }
    }
}
