//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sklepy
    {
        public t_sklepy()
        {
            this.t_produkty = new HashSet<t_produkty>();
            this.t_zamowienia = new HashSet<t_zamowienia>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Wlasciciel_id_user { get; set; }
        public Nullable<int> NumerKonta { get; set; }
    
        public virtual ICollection<t_produkty> t_produkty { get; set; }
        public virtual t_users t_users { get; set; }
        public virtual ICollection<t_zamowienia> t_zamowienia { get; set; }
    }
}
