//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_substancje
    {
        public t_substancje()
        {
            this.t_sklad = new HashSet<t_sklad>();
        }
    
        public int pk_substancje_id_num { get; set; }
        public string nazwa_char { get; set; }
    
        public virtual ICollection<t_sklad> t_sklad { get; set; }
    }
}
